model_type: 1 #1 = vanilla cycle gan, 2 = u-net, 3 = ffa-net
input_nc: 3
patch_size: 256

#0 - 24GB, 1 - 32GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [64, 96, 24, 16] #amount of images to accumulate before backprop
load_size: [64, 96, 24, 16] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 6
weight_decay: 0.0
dropout_rate: 0.0
augment_key: ["random_noise"]

g_lr: 0.0002
d_lr: 0.0005
min_epochs: 60
max_epochs: 65

dataset_version: "v46_places"
dataset_repeats: 1
mix_istd: 0.5




