#!/bin/bash
#SBATCH -J R_7
#SBATCH --partition=gpu
#SBATCH --qos=12c-1h_2gpu
#SBATCH --cpus-per-task=6
#SBATCH -G 1
#SBATCH --ntasks=1
#SBATCH --output=script_7.out
#SBATCH --mail-user=neil.delgallego@dlsu.edu.ph
#SBATCH --mail-type=END

ITERATION=11
echo "CUDA_DEVICE=/dev/nvidia/$CUDA_VISIBLE_DEVICES"
nvidia-smi

# prepare working environment
module load anaconda/3-2021.11
module load cuda/10.1_cudnn-7.6.5

source activate NeilGAN_V2

srun python iid_train.py \
--iteration=$ITERATION \
--server_config=1 \
--batch_size=512 \
--patch_size=64 \
--plot_enabled=0 \
--version_name="iid_networkv5.03" --min_epochs=50 --net_config=2 --num_blocks=0 \
--da_enabled=1 --da_version_name="embedding_v5.00_5" \
--img_to_load=-1 --load_previous=0


conda deactivate