model_type: 5
input_nc: 3
patch_size: 256

#0 - 24GB, 1 - 32GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [24, 32, 12, 8] #amount of images to accumulate before backprop
load_size: [24, 32, 12, 8] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 3
weight_decay: 0.0
dropout_rate: 0.0
augment_key: ["none"]
use_shadow_map: False
mix_istd: 0.5
mix_srd: 0.5

g_lr: 0.0002
d_lr: 0.0005
min_epochs: 20
max_epochs: 25

dataset_version: "v69_places"
dataset_repeats: 3