model_type: 1
input_nc: 3
patch_size: 256

#0 - 24GB, 1 - 32GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [64, 72, 32, 12] #amount of images to accumulate before backprop
load_size: [64, 72, 32, 12] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 6
weight_decay: 0.0
dropout_rate: 0.0
augment_key: ["none"]
use_shadow_map: False

g_lr: 0.0002
d_lr: 0.0005
max_epochs: 40
epoch_tolerance: 15

dataset_version: "v_srd"
dataset_repeats: 10
dataset_val_ref: "srd"