model_type: 5
input_nc: 3
patch_size: 64

#0 - 24GB, 1 - 32GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [320, 320, 128, 64] #amount of images to accumulate before backprop
load_size: [320, 320, 128, 64] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 3
weight_decay: 0.0
dropout_rate: 0.0
augment_key: ["augmix", "random_noise", "random_exposure"]
use_shadow_map: False

g_lr: 0.0002
d_lr: 0.0005
min_epochs: 150
max_epochs: 150

dataset_version: "v_istd+srd"
dataset_repeats: 10