model_type: 2
input_nc: 4
patch_size: 256

#0 - 24GB, 1 - 32GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [256, 256, 128, 64] #amount of images to accumulate before backprop
load_size: [256, 256, 128, 64] #amount of images to load in GPU. load_size <= batch_size


num_blocks: 2
weight_decay: 0.0
dropout_rate: 0.0
augment_key: ["none"]

g_lr: 0.0002
d_lr: 0.0005
max_epochs: 40
epoch_tolerance: 15

dataset_version: "v66_places"
dataset_repeats: 3